# Generated by Django 5.0 on 2023-12-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='category',
            new_name='type',
        ),
        migrations.AddField(
            model_name='about',
            name='img_webp',
            field=models.ImageField(blank=True, upload_to='index/about/img_webp'),
        ),
        migrations.AddField(
            model_name='course',
            name='img_webp',
            field=models.ImageField(blank=True, upload_to='index/courses/img_webp'),
        ),
        migrations.AddField(
            model_name='event',
            name='img_webp',
            field=models.ImageField(blank=True, upload_to='index/events/img_webp'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='img_webp',
            field=models.ImageField(blank=True, upload_to='index/quotes/img_webp'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='img_webp',
            field=models.ImageField(blank=True, upload_to='index/teachers/img_webp'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='img_webp',
            field=models.ImageField(blank=True, upload_to='index/testimonials/img_webp'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='index/teachers/img'),
        ),
    ]
