# Generated by Django 5.0 on 2023-12-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_category_testimonials_type_about_img_webp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('active', models.BooleanField(blank=True, default=False)),
                ('courses', models.ManyToManyField(to='index.course')),
                ('teachers', models.ManyToManyField(to='index.teacher')),
            ],
        ),
    ]
